pipeline {
  agent any
  stages {
    stage('checkout'){
      steps {
         checkout scm
      }
    }
    stage('start nginx'){
      steps {
         sh 'ansible-playbook ansible-nginx/deploy.yaml -i ansible-nginx/hosts.ini'
      }
    }
  }
    post {
        success {
            echo 'Pipeline + Ansible executed successfully ✅'
        }
        failure {
            echo 'Pipeline failed 💥'
        }
  }
}
