pipeline {

  agent any

  stages {
  
    stage('Checkout') {
      echo "Checking out code in SCM"
      checkout scm
    }
    stage('Build application') {
     echo "Running application"
     sh './app.sh'
    }
    stage('Testing application') {
     echo "Testing application"
     sh './test.sh'
    }

  }
}
