pipeline {

  agent any

  stages {
  
    stage('Checkout') {
      steps {
        echo "Checking out code in SCM"
        checkout scm
      }
    }
    stage('Build application') {
      steps {
        echo "Running application"
        sh './app.sh'
      }
    }
    stage('Testing application') {
      steps {
        echo "Testing application"
        sh './test.sh'
      }
    }

  }
}
