apiVersion: v1
kind: Service
metadata:
  name: java-spring-argo-service
spec:
  type: NodePort
  selector:
    app: java-spring-argo-pod
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30085
