pipeline {
  agent any
  stages {
    stage('Clean Workspace') {
      steps {
        deleteDir() // deletes everything in the workspace
      }
    }
    stage('checkout') {
      steps {
        git url: 'https://github.com/anvithaprabhu8/Jenkins-CICD', branch: 'main'
      }
    }
    stage('Build and test'){
      steps {
        sh 'cd java-argo-project && mvn clean package' 
      }
    }
    stage('Sonarqube Analysis') {
      steps {
        withSonarQubeEnv('SonarQubeServer') {
        sh 'cd java-argo-project && mvn sonar:sonar'
        }
      }
    }
  }
}
