pipeline {
    agent any
    environments {
        IMAGE_NAME = "anvithaprabhu98/myjavaargo"
        DOCKER_CREDENTIALS = "dockerhub-creds"
    }
  stages {
    stage('Clean Workspace') {
      steps {
        deleteDir() // deletes everything in the workspace
      }
    }
    stage('checkout') {
      steps {
        git url: 'https://github.com/anvithaprabhu8/Jenkins-CICD', branch: 'main'
      }
    }
    stage('Build and test'){
      steps {
        sh 'cd java-argo-project && mvn clean package' 
      }
    }
    stage('Sonarqube Analysis') {
      steps {
        withSonarQubeEnv('SonarQubeServer') {
        sh 'cd java-argo-project && mvn sonar:sonar'
        }
      }
    }
   stage('Docker build image') {
     steps {
       sh 'echo building docker image'
       def image = docker.build("${IMAGE_NAME}:${env.BUILD_NUMBER}")
     }
   }
   stage('Docker push image') {
     steps {
       sh 'echo push docker image'
       docker.withRegistry('', "${DOCKER_CREDENTIALS}") {
       docker.image("${IMAGE_NAME}:${env.BUILD_NUMBER}").push()
      }
     } 
   }
}
