pipeline {
    agent any
    environment {
        IMAGE_NAME = "anvithaprabhu98/myjavaargo"
        DOCKER_CREDENTIALS = "dockerhub-creds"
    }
  stages {
    stage('Clean Workspace') {
      steps {
        deleteDir() // deletes everything in the workspace
      }
    }
    stage('checkout') {
      steps {
        git url: 'https://github.com/anvithaprabhu8/Jenkins-CICD', branch: 'main'
      }
    }
    stage('Build and test'){
      steps {
        sh 'cd java-argo-project && mvn clean package' 
      }
    }
    stage('Sonarqube Analysis') {
      steps {
        withSonarQubeEnv('SonarQubeServer') {
        sh 'cd java-argo-project && mvn sonar:sonar'
        }
      }
    }
   stage('Docker build image') {
     steps {
       dir('java-argo-project') {
       sh 'echo building docker image'
       script {
         def image = docker.build("${IMAGE_NAME}:${env.BUILD_NUMBER}")
       }
      }     
     }
   }
   stage('Docker push image') {
     steps {
       sh 'echo push docker image'
       script {
        docker.withRegistry('', "${DOCKER_CREDENTIALS}") {
        docker.image("${IMAGE_NAME}:${env.BUILD_NUMBER}").push()
        }
       }     
      } 
    }
   stage('Update image in Manifest'){
     environment{
       GIT_REPO_NAME= "Jenkins-CICD"
     }
     steps{
       withCredentials([usernamePassword(
            credentialsId: 'my-github',
            usernameVariable: 'GIT_USER',
            passwordVariable: 'GIT_TOKEN'
        )]) {
            sh '''
                git config user.name "anvithaprabhu"
                git config user.email "anvithaprabhu8@gmail.com"

                sed -i "s/tag/${BUILD_NUMBER}/g" java-argo-project-manifest/deployment.yaml

                git add java-argo-project-manifest/deployment.yaml
                git commit -m "Updated image in deployment file with tag ${BUILD_NUMBER}"
                git push https://${GIT_USER}:${GIT_TOKEN}@github.com/${GIT_USER}/${GIT_REPO_NAME} HEAD:main
            '''
     }
   } 
  }
}    
    
